server.port: 3000
spring:
  profiles:
    active: dev
  application:
    name: service-user
  datasource:
    url: jdbc:postgresql://user_db:5432/users?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
    show-sql: true
    generate-ddl: true #create database if not exists